* Emacs config

** Quickstart

1. Clone this repo into =~/.emacs.d= (or =%APPDATA%/.emacs.d= on Windows).
2. Start Emacs once to let packages install.
3. Run =M-x my/treesit-install= to build tree-sitter grammars.
4. Run =M-x eaf-install= if you use EAF.

** Installation

This config assumes Emacs 30+ (built-in tree-sitter).

*** Linux (build from source)

#+begin_src bash
  git clone https://git.savannah.gnu.org/git/emacs.git
  cd emacs
  git checkout emacs-30.2
  ./autogen.sh
  ./configure --prefix=/usr/local --with-x --with-x-toolkit=gtk3 --without-pgtk --with-native-compilation --with-tree-sitter --with-modules --with-cairo --with-imagemagick --with-xft
  make -j$(nproc)
  sudo make install
#+end_src

*** Windows (Chocolatey)

#+begin_src bash
  choco install emacs
#+end_src

** Requirements

*** Windows

- [[https://www.libvips.org/install.html][libvips]] (Dirvish image preview)
- Extra tools:
#+begin_src bash
  choco install gnuwin
#+end_src

*** Shell tools

- [[https://bun.com/docs/installation][bun]] and [[https://nodejs.org/en/download][npm]]
- [[https://www.python.org/downloads/][python]] and [[https://docs.astral.sh/uv/getting-started/installation/][uv]]
- [[https://github.com/BurntSushi/ripgrep#installation][ripgrep]]
#+begin_src bash
  choco install ripgrep
  sudo dnf install ripgrep
  sudo pacman -S ripgrep
#+end_src

*** Optional

- Maple Mono / Maple Mono NF (GUI font)
- mpv (for mpvi)

** LSP (lsp-bridge)

*** Python deps

#+begin_src bash
  pip3 install epc orjson sexpdata six setuptools paramiko rapidfuzz watchdog packaging
#+end_src

*** Language server mapping

- ts/js: =tsls_oxlint_oxfmt=
- py: =ty_ruff=

*** Install tools

#+begin_src bash
  bun install -g typescript-language-server typescript oxlint oxfmt vscode-langservers-extracted

  uv tool install ruff ty
#+end_src

** Windows notes

- Git is expected at =C:/Program Files/Git/usr/bin= (added to PATH in =init.el=).
- vips is expected at C:/Program Files/vips/bin
- =bash-completion= uses WSL when available.

- Set ctrl to caps
  #+begin_src pwsh
    $hexified = "00,00,00,00,00,00,00,00,02,00,00,00,1d,00,3a,00,00,00,00,00".Split(',') | % { "0x$_"};
    $kbLayout = 'HKLM:\System\CurrentControlSet\Control\Keyboard Layout';
    New-ItemProperty -Path $kbLayout -Name "Scancode Map" -PropertyType Binary -Value ([byte[]]$hexified);
  #+end_src
